/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/message` | `/message`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/post` | `/post`; params?: Router.UnknownInputParams; } | { pathname: `/message/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } } | { pathname: `/note/[noteId]`, params: Router.UnknownInputParams & { noteId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/message` | `/message`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/post` | `/post`; params?: Router.UnknownOutputParams; } | { pathname: `/message/[roomId]`, params: Router.UnknownOutputParams & { roomId: string; } } | { pathname: `/note/[noteId]`, params: Router.UnknownOutputParams & { noteId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/message${`?${string}` | `#${string}` | ''}` | `/message${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my${`?${string}` | `#${string}` | ''}` | `/my${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/post${`?${string}` | `#${string}` | ''}` | `/post${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/message` | `/message`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/post` | `/post`; params?: Router.UnknownInputParams; } | `/message/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/note/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/message/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } } | { pathname: `/note/[noteId]`, params: Router.UnknownInputParams & { noteId: string | number; } };
    }
  }
}
